spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: product
    password: product
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true